### ISSUE TITLE
things to add

### ISSUE THREAD

**Issue by kamariana** [zerobug110/muhammed-portfolio#1]
Nice work brother,
please do the following:

- add a .ignore to ignore node_modules folder .vscode and other (if the project is base node, better set this up while you creating the repo)
- add a linkt to your portfolio in the readme so that I don't have to download to see, I can click on the link.

get a domian on zerobug.gm and host your portfolio for free, I can help you with the domain

stay blessed

**Comment by mahad8v** [comment]
thanks i will have them added
